// examples/pdf-react/src/App.jsx
import React, { useState, useEffect } from 'react';
import { generate } from '@pdfme/generator';
import { BLANK_A4_PDF } from '@pdfme/common';
import { convertIVSToExternal, hasIVSCharacters, countIVSCharacters, getIVSCharacterDetails } from 'ivs-font-processor';
import './App.css';

const App = () => {
  const [textValue, setTextValue] = useState('\u6AC2\uDB40\uDD01 \u7027\uDB40\uDD07 \u6406\uDB40\uDD03 \u3404\uDB40\uDD00 - \u3404\uDB40\uDD01 - \u3404\uDB40\uDD02 - \u3732\udb40\udd01 - \u4672\udb40\udd00');
  const [fonts, setFonts] = useState({});

  // フォントを読み込み
  useEffect(() => {
    const loadFonts = async () => {
      try {
        // IPA明朝フォント
        const ipaResponse = await fetch('./fonts/ipam.ttf');
        const ipaBuffer = await ipaResponse.arrayBuffer();
        
        // IVS外字フォント
        const ivsResponse = await fetch('./fonts/ipa-ivs-external.ttf');
        const ivsBuffer = await ivsResponse.arrayBuffer();
        
        setFonts({
          'IPA明朝': {
            data: ipaBuffer,
            fallback: true,
          },
          'IPA-IVS-External': {
            data: ivsBuffer
          }
        });
        
        console.log('フォント読み込み完了');
      } catch (error) {
        console.error('フォント読み込みエラー:', error);
      }
    };
    
    loadFonts();
  }, []);

  // 計算されたプロパティ（Vueのcomputed相当）
  const displayText = convertIVSToExternal(textValue);
  const hasIVS = hasIVSCharacters(textValue);
  const ivsCount = countIVSCharacters(textValue);
  const ivsDetails = getIVSCharacterDetails(textValue);

  const generatePDF = async () => {
    try {
      if (Object.keys(fonts).length === 0) {
        alert('フォントがまだ読み込まれていません。しばらくお待ちください。');
        return;
      }
      // 変換されたテキストを確認
      const convertedText = convertIVSToExternal(textValue) || "（未入力）";
      console.log('元のテキスト:', textValue);
      console.log('変換後のテキスト:', convertedText);

      // PDFテンプレート定義（pdfme v4形式）
      const template = {
        basePdf: BLANK_A4_PDF,
        schemas: [
          {
            title: {
              type: 'text',
              position: { x: 50, y: 50 },
              width: 100,
              height: 10,
              fontSize: 24,
              fontName: 'IPA明朝',
              fontColor: '#000000'
            },
            nomalText: {
              type: 'text',
              position: { x: 50, y: 70 },
              width: 100,
              height: 15,
              fontSize: 18,
              fontName: 'IPA明朝',
              fontColor: '#000000'
            },
            puaText: {
              type: 'text',
              position: { x: 50, y: 80 },
              width: 100,
              height: 15,
              fontSize: 18,
              fontName: 'IPA-IVS-External',
              fontColor: '#000000'
            }
          }
        ]
      };

      // 入力データ
      const inputs = [
        {
          title: 'Hello from React + pdfme',
          nomalText: 'ISV:'+ textValue,
          puaText: 'PUA:' + convertedText,
        }
      ];

      // PDF生成（pdfme v5形式）
      const pdf = await generate({
        template,
        inputs,
        options: {
          font: fonts
        }
      });

      // ダウンロード
      const blob = new Blob([pdf], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'ivs-react-example.pdf';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

    } catch (error) {
      console.error('PDF生成エラー:', error);
      alert('PDF生成中にエラーが発生しました。');
    }
  };

  return (
    <div className="app">
      <h1>IVS Font Processor - React + pdfme Example</h1>
      
      <div className="input-section">
        <input
          type="text"
          value={textValue}
          onChange={(e) => setTextValue(e.target.value)}
          placeholder="テキストを入力してください（IVS文字対応）"
          className="text-input"
        />
      </div>

      {textValue && (
        <div className="preview">
          <div className="preview-label">プレビュー（変換後）:</div>
          <div className="preview-text">{displayText}</div>
          
          {hasIVS && (
            <div className="ivs-info">
              <div className="ivs-summary">
                <strong>🔄 IVS文字が{ivsCount}文字検出されました</strong>
              </div>
              <div className="ivs-details">
                {ivsDetails.map((detail, index) => (
                  <div key={index} className="ivs-detail-item">
                    <div className="char-display">
                      <span className="ivs-char">{detail.ivs}</span>
                      <span className="char-code">{detail.ivsCode}</span>
                    </div>
                    <span className="arrow">→</span>
                    <div className="char-display">
                      <span className="external-char">{detail.external}</span>
                      <span className="char-code">{detail.externalCode}</span>
                    </div>
                    <span className="count">({detail.count}個)</span>
                  </div>
                ))}
              </div>
              <small className="ivs-note">PDF生成時に外字フォントで表示されます。</small>
            </div>
          )}
        </div>
      )}

      <button onClick={generatePDF} className="generate-btn">
        PDF生成 (pdfme)
      </button>
    </div>
  );
};

export default App;

// examples/pdf/src/App.vue
<template>
  <div id="app">
    <h1>Hello</h1>
    <input type="text" v-model="textValue" placeholder="テキストを入力してください（IVS文字対応）" />
    <div class="preview" v-if="textValue">
      <div class="preview-label">プレビュー（変換後）:</div>
      <div class="preview-text">{{ displayText }}</div>
      <div class="ivs-info" v-if="hasIVS">
        <div class="ivs-summary">
          <strong>🔄 IVS文字が{{ ivsCount }}文字検出されました</strong>
        </div>
        <div class="ivs-details">
          <div v-for="detail in ivsDetails" :key="detail.external" class="ivs-detail-item">
            <div class="char-display">
              <span class="ivs-char">{{ detail.ivs }}</span> 
              <span class="char-code">{{ detail.ivsCode }}</span>
            </div>
            <span class="arrow">→</span>
            <div class="char-display">
              <span class="external-char">{{ detail.external }}</span>
              <span class="char-code">{{ detail.externalCode }}</span>
            </div>
            <span class="count">({{ detail.count }}個)</span>
          </div>
        </div>
        <small class="ivs-note">PDF生成時に外字フォントで表示されます。</small>
      </div>
    </div>
    <button @click="generatePDF">PDF生成</button>
  </div>
</template>

<script>
import { Core, PdfExport, XlsxExport } from '@grapecity/activereports'
import { convertIVSToExternal, hasIVSCharacters, countIVSCharacters, getIVSCharacterDetails } from 'ivs-font-processor'

export default {
  name: 'App',
  data() {
    return {
      textValue:  '\u6AC2\uDB40\uDD01 \u7027\uDB40\uDD07 \u6406\uDB40\uDD03 \u3404\uDB40\uDD00 - \u3404\uDB40\uDD01 - \u3404\uDB40\uDD02 - \u3732\udb40\udd01 - \u4672\udb40\udd00'
    }
  },
  computed: {
    displayText() {
      return convertIVSToExternal(this.textValue)
    },
    hasIVS() {
      return hasIVSCharacters(this.textValue)
    },
    ivsCount() {
      return countIVSCharacters(this.textValue)
    },
    ivsDetails() {
      return getIVSCharacterDetails(this.textValue)
    }
  },
  methods: {
    async generatePDF() {
      try {
        // フォントの登録（シンボリックリンク経由）
        const ipaFont = {
          name: "IPA明朝",
          source: "/fonts/ipam.ttf"
        }
        await Core.FontStore.registerFonts(ipaFont)
        console.log('IPA明朝フォント登録完了')
        
        // IVS外字フォントの登録（シンボリックリンク経由）
        const ivsExternalFont = {
          name: "IPA-IVS-External",
          source: "/fonts/ipa-ivs-external.ttf"
        }
        await Core.FontStore.registerFonts(ivsExternalFont)
        console.log('IVS外字フォント登録完了')
        
        // 登録されたフォントの確認
        const registeredFonts = Core.FontStore.getFonts()
        console.log('登録されたフォント:', registeredFonts)
        
        // 変換されたテキストを確認
        const convertedText = convertIVSToExternal(this.textValue) || "（未入力）"
        console.log('元のテキスト:', this.textValue)
        console.log('変換後のテキスト:', convertedText)
        console.log('変換後の文字コード:', Array.from(convertedText).map(c => `U+${c.codePointAt(0).toString(16).toUpperCase()}`))
        
        // レポート定義を作成
        const reportDef = {
          Type: "report",
          Version: "17.1.0.0",
          Name: "HelloReport",
          Body: {
            ReportItems: [
              {
                Type: "textbox",
                Name: "HelloTextBox",
                Value: "Hello",
                Style: {
                  FontFamily: "IPA明朝",
                  FontSize: "24pt",
                  Color: "#000000",
                  TextAlign: "Center"
                },
                Top: "1in",
                Left: "2in",
                Width: "4in",
                Height: "0.5in"
              },
              {
                Type: "textbox",
                Name: "UserInputTextBox",
                Value: convertedText,
                Style: {
                  FontFamily: "IPA-IVS-External",
                  FontSize: "18pt",
                  Color: "#000000",
                  TextAlign: "Center"
                },
                Top: "2in",
                Left: "2in",
                Width: "4in",
                Height: "0.5in"
              }
            ]
          },
          PageSettings: {
            Size: {
              Width: "8.27in",
              Height: "11.69in"
            },
            Margins: {
              Top: "1in",
              Bottom: "1in",
              Left: "1in",
              Right: "1in"
            }
          }
        }

        // レポートを実行
        const report = new Core.PageReport()
        await report.load(reportDef)
        const document = await report.run()
        
        // PDFエクスポート
 	const result = await PdfExport.exportDocument(document)
        
        // ダウンロード
        this.downloadPDF(result.data, 'hello-report.pdf')
        
      } catch (error) {
        console.error('PDF生成エラー:', error)
        alert('PDF生成中にエラーが発生しました。')
      }
    },
    
    downloadPDF(data, filename) {
      const blob = new Blob([data], { type: 'application/pdf' })
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = filename
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(url)
    }
  }
}
</script>

<style>
@font-face {
  font-family: 'IPA明朝';
  src: url('/fonts/ipam.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'IPA-IVS-External';
  src: url('/fonts/ipa-ivs-external.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
}

#app {
  font-family: 'IPA明朝', serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

input {
  font-family: 'IPA明朝', serif;
  font-size: 16px;
  padding: 8px;
  margin-top: 20px;
}

button {
  font-family: 'IPA明朝', serif;
  font-size: 16px;
  padding: 10px 20px;
  margin-top: 20px;
  background-color: #42b883;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  display: block;
  margin-left: auto;
  margin-right: auto;
}

button:hover {
  background-color: #369870;
}

.preview {
  margin: 20px 0;
  padding: 15px;
  border: 1px solid #ddd;
  border-radius: 4px;
  background-color: #f9f9f9;
}

.preview-label {
  font-weight: bold;
  margin-bottom: 5px;
  color: #2c3e50;
}

.preview-text {
  font-family: 'IPA-IVS-External', 'IPA明朝', serif;
  font-size: 18px;
  padding: 10px;
  background-color: white;
  border: 1px solid #ccc;
  border-radius: 3px;
  margin-bottom: 10px;
}

.ivs-info {
  color: #42b883;
  background-color: #f0f9ff;
  border: 1px solid #42b883;
  border-radius: 4px;
  padding: 10px;
  margin-top: 10px;
}

.ivs-summary {
  margin-bottom: 8px;
}

.ivs-details {
  margin: 8px 0;
}

.ivs-detail-item {
  display: flex;
  align-items: center;
  margin: 6px 0;
  font-family: 'IPA-IVS-External', 'IPA明朝', monospace;
}

.char-display {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 0 8px;
}

.ivs-char {
  background-color: #fff3cd;
  padding: 4px 6px;
  border-radius: 3px;
  font-weight: bold;
  font-size: 18px;
  margin-bottom: 2px;
}

.external-char {
  background-color: #d1ecf1;
  padding: 4px 6px;
  border-radius: 3px;
  font-family: 'IPA-IVS-External', monospace;
  font-size: 18px;
  margin-bottom: 2px;
}

.char-code {
  font-size: 10px;
  color: #666;
  font-family: monospace;
  text-align: center;
}

.arrow {
  font-size: 16px;
  color: #666;
  margin: 0 4px;
}

.count {
  font-size: 0.9em;
  color: #666;
}

.ivs-note {
  display: block;
  margin-top: 8px;
  font-style: italic;
  color: #666;
}
</style>
